import {
  MockCustomers,
  MockMonthlyType,
  MockFixedExpense,
  ChartAccountsType,
  MockTransactionsType,
} from "@/lib/types";

export const openingBalance = [
  { date: "2025-08-16", openingBalance: 1.40, bank: "Cora" },
  { date: "2025-08-24", openingBalance: 3.06, bank: "Asaas" }
];

export const mockCustomers: MockCustomers[] = [
  {
    cnpj: "31.189.690/0001-00",
    companyName: "T. C DE SOUSA & CIA LTDA ",
    fantasyName: "Diamond",
    email: "",
    phone: "",
    signedContract: "",
    signedDate: "",
    dueDate: "",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 3000.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "1028",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "54.687.930/0001-94",
    companyName: "FRAGA E REZENDE LTDA",
    fantasyName: "Farmaformula",
    email: "",
    phone: "",
    signedContract: "",
    signedDate: "",
    dueDate: "",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 2000.0,
    terminationClause: "",
    address: {
      avenue: "",
      street: "Rua 31 de Julho",
      neighborhood: "Centro",
      number: "200",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  { 
    cnpj: "05.356.440/0001-08",
    companyName: "J B FERREIRA DE SA",
    fantasyName: "J. Lanches Pizzaria Delivery",
    email: "",
    phone: "",
    signedContract: "",
    signedDate: "",
    dueDate: "",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 2500.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "2210",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "43.213.724/0001-08",
    companyName: "F OLIVER AGUIAR LOPES LTDA",
    fantasyName: "Casa de Cecília",
    email: "",
    phone: "",
    signedContract: "",
    signedDate: "",
    dueDate: "",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 3000.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "1048",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "26.158.183/0004-04",
    companyName: "KAROLYNE SIQUEIRA FREIRE LTDA",
    fantasyName: "Perolab",
    email: "",
    phone: "",
    signedContract: "",
    signedDate: "",
    dueDate: "",
    contractTime: "",
    contractStatus: "suspenso",
    monthlyFee: 2300.0,
    terminationClause: "",
    address: {
      avenue: "",
      street: "R Maria do Socorro Frota e Fontenele",
      neighborhood: "Regis Diniz",
      number: "381",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  }
];


export const mockExpensesFixed: MockFixedExpense[] = [
  {
    description: "João Vitor",
    paymentMethod: "Transferência",
    amount: 1500.0,
    dueDate: "2025-10-01",
    observation: "Carteira assinada"
  },
  {
    description: "Saymon",
    paymentMethod: "Transferência",
    amount: 800.0,
    dueDate: "2025-10-01",
    observation: "Estagiário"
  },
  {
    description: "Mayane",
    paymentMethod: "Transferência",
    amount: 1500.0,
    dueDate: "2025-10-01",
    observation: "Sócio sem recolhimento"
  },
  {
    description: "Júlio César",
    paymentMethod: "Transferência",
    amount: 4000.0,
    dueDate: "2025-10-01",
    observation: "Sócio sem recolhimento"
  },
  {
    description: "INSS",
    paymentMethod: "Guia",
    amount: 0.0,
    dueDate: "2025-09-20",
    observation: "Encargo CLT"
  },
  {
    description: "FGTS",
    paymentMethod: "Guia",
    amount: 0.0,
    dueDate: "2025-09-01",
    observation: "Encargo CLT"
  },
  {
    description: "Seguro",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Encargo estagiário"
  },
  {
    description: "Agência",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Encargo estagiário"
  },
  {
    description: "Provisão 13º",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Provisão mensal CLT"
  },
  {
    description: "Provisão Féria",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Provisão mensal CLT"
  },
  {
    description: "Internet",
    paymentMethod: "Boleto",
    amount: 92.17,
    dueDate: "2025-10-10",
    observation: ""
  },
  {
    description: "Aluguel + Energia",
    paymentMethod: "Desconto",
    amount: 700.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Software - Adobe (cartão hype)",
    paymentMethod: "Cartão",
    amount: 92.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Software - Google",
    paymentMethod: "Cartão",
    amount: 105.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Tripé",
    paymentMethod: "Cartão",
    amount: 49.44,
    dueDate: "2025-10-20",
    observation: "18x (2/18) - Finaliza (12/2026)"
  },
  {
    description: "Treinamento Don",
    paymentMethod: "Cartão",
    amount: 149.44,
    dueDate: "2025-10-20",
    observation: "12x (2/12) - Finaliza (06/2026)"
  },
  {
    description: "DAF/Gaveteiros",
    paymentMethod: "Cartão",
    amount: 66.93,
    dueDate: "2025-10-20",
    observation: "3x (2/3) - Finaliza (09/2025)"
  },
  {
    description: "Ar-condicionado",
    paymentMethod: "Cartão",
    amount: 291.83,
    dueDate: "2025-10-20",
    observation: "10x (8/10) - Finaliza (10/2025)"
  },
  {
    description: "Mensalidade BPO",
    paymentMethod: "Boleto",
    amount: 300.0,
    dueDate: "2025-10-25",
    observation: "A partir de setembro"
  },
  {
    description: "Mensalidade Contabilidade",
    paymentMethod: "Boleto",
    amount: 80.0,
    dueDate: "2025-10-25",
    observation: "Após alteração"
  },
  {
    description: "Simples Nacional",
    paymentMethod: "Guia",
    amount: 600.0,
    dueDate: "2025-10-20",
    observation: "6% do faturamento"
  },
  {
    description: "Processo de alteração contábil",
    paymentMethod: "Transferência",
    amount: 1000.0,
    dueDate: "A definir",
    observation: "Apenas uma vez"
  },
  {
    description: "Taxa de processo JUCEC",
    paymentMethod: "Boleto",
    amount: 260.0,
    dueDate: "",
    observation: "Apenas quando iniciar o processo"
  },
  {
    description: "Débitos antigos MEI",
    paymentMethod: "Guia",
    amount: 1236.08,
    dueDate: "",
    observation: "309.02/mês (4x)"
  },
  {
    description: "MEI 2025",
    paymentMethod: "Guia",
    amount: 471.17,
    dueDate: "",
    observation: "Em aberto para 2025"
  },
];

// function createMockCategories(data: MockTransactionsType[]) {
//   const categoryMap = new Map<string, number>();

//   data.forEach((item) => {
//     categoryMap.set(item.category, (categoryMap.get(item.category) || 0) + item.amount);
//   });

//   return Array.from(categoryMap.entries()).map(([name, value]) => ({ name, value }));
// }

function createMockMonthly(data: MockTransactionsType[]) {
  const monthName = [
    { name: 'Jan', number: 0 },
    { name: 'Fev', number: 1 }, 
    { name: 'Mar', number: 2 }, 
    { name: 'Abr', number: 3 },
    { name: 'Mai', number: 4 },
    { name: 'Jun', number: 5 },
    { name: 'Jul', number: 6 },
    { name: 'Ago', number: 7 },
    { name: 'Set', number: 8 }, 
    { name: 'Out', number: 9 },
    { name: 'Nov', number: 10 },
    { name: 'Dez', number: 11 }
  ];
  
  const result: MockMonthlyType[] = [];

  const dates = data.map((item) => new Date(item.date)).sort((a, b) => a.getTime() - b.getTime());
  const minDate = dates[0];
  const maxDate = dates[dates.length - 1];

  for (let i = minDate.getMonth(); i <= maxDate.getMonth(); i++) {
    const filtered = data.filter((register) => new Date(register.date).getMonth() === i);

    const variableRevenue = filtered
      .filter((register) => register.typeId === 1 && register.accountId !== 3)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const fixedRevenue = filtered
      .filter((register) => register.typeId === 1 && register.accountId === 3)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const cost = filtered
      .filter((register) => register.typeId === 3)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const expense = filtered
      .filter((register) => register.typeId === 2)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);

    result.push({ 
      month: monthName[i].name, 
      date: `2025-${String(i+1).padStart(2, "0")}-01`, 
      fixedRevenue, 
      variableRevenue,
      expense,
      cost,
    });
  }

  return result;
}

export const mockTransactions: MockTransactionsType[] = [
  { 
    id: "tx-00101",
    date: "2025-08-24",
    description: "Saldo Inicial",
    customerId: "",
    customer: "",
    history: "",
    typeId: 0,
    type: "",
    amount: 3.06,
    accountId: 0,
    bank: "asaas"
  },
  { 
    id: "tx-00111",
    date: "2025-08-16",
    description: "Saldo Inicial",
    customerId: "",
    customer: "",
    history: "",
    typeId: 0,
    type: "",
    amount: 1.40,
    accountId: 0,
    bank: "cora"
  },
  { 
    id: "tx-001",
    date: "2025-08-22",
    description: "Transf Pix recebida",
    customerId: "43.213.742/0001-08",
    customer: "F OLIVER AGUIAR LOPES LTDA",
    history: "Mensalidade",
    typeId: 1,
    type: "Crédito",
    amount: 3000.0,
    accountId: 3,
    bank: "cora"
  },
  {
    id: "tx-002",
    date: "2025-08-22",
    description: "Transf Pix recebida",
    customerId: "31.189.690/0001-00",
    customer: "T. C. DE SOUSA & CIA LTDA",
    history: "Mensalidade",
    typeId: 1,
    type: "Crédito",
    amount: 1000.0,
    accountId: 3,
    bank: "cora"
  },
  {
    id: "tx-003",
    date: "2025-08-26",
    description: "Transf Pix recebida",
    customerId: "31.189.690/0001-00",
    customer: "T. C. DE SOUSA & CIA LTDA",
    history: "Mensalidade",
    typeId: 1,
    type: "Crédito",
    amount: 1000.0,
    accountId: 3,
    bank: "cora"
  },
  {
    id: "tx-004",
    date: "2025-08-28",
    description: "Transf Pix recebida",
    customerId: "26.719.797/0001-75",
    customer: "SANTOS E CUNHA L…",
    history: "Mensalidade",
    typeId: 1,
    type: "Crédito",
    amount: 1000.0,
    accountId: 3,
    bank: "cora"
  },
  {
    id: "tx-005",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Gaveteiros",
    typeId: 2,
    type: "Débito",
    amount: 66.93,
    accountId: 77,
    bank: "cora"
  },
  {
    id: "tx-006",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Ar Condicionado",
    typeId: 2,
    type: "Débito",
    amount: 291.83,
    accountId: 73,
    bank: "cora"
  },
  {
    id: "tx-007",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Tripé",
    typeId: 2,
    type: "Débito",
    amount: 49.44,
    accountId: 73,
    bank: "cora"
  },
  {
    id: "tx-008",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Treinamento",
    typeId: 2,
    type: "Débito",
    amount: 149.70,
    accountId: 98,
    bank: "cora"
  },
  {
    id: "tx-009",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Programa de Edição",
    typeId: 3,
    type: "Débito",
    amount: 95.0,
    accountId: 25,
    bank: "cora"
  },
  {
    id: "tx-010",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Sistemas Contratados",
    typeId: 2,
    type: "Débito",
    amount: 27.95,
    accountId: 90,
    bank: "cora"
  },
  {
    id: "tx-011",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Sistemas Contratados",
    typeId: 2,
    type: "Débito",
    amount: 24.47,
    accountId: 90,
    bank: "cora"
  },
  {
    id: "tx-012",
    date: "2025-08-23",
    description: "Pgto QR Code Pix",
    customerId: "10.573.521/0001-91",
    customer: "MERCADO PAGO IN…",
    history: "Sistemas Contratados",
    typeId: 2,
    type: "Débito",
    amount: 324.22,
    accountId: 90,
    bank: "cora"
  },
  {
    id: "tx-013",
    date: "2025-08-25",
    description: "Transf Pix recebida",
    customerId: "41.655.312/0001-10",
    customer: "41.655.312 JULIO C…",
    history: "Transferência",
    typeId: 1,
    type: "Crédito",
    amount: 2500.0,
    accountId: 105,
    bank: "cora"
  },
  {
    id: "tx-014",
    date: "2025-08-26",
    description: "Transf Pix recebida",
    customerId: "41.655.312/0001-10",
    customer: "41.655.312 JULIO C…",
    history: "Transferência",
    typeId: 1,
    type: "Crédito",
    amount: 2299.0,
    accountId: 105,
    bank: "cora"
  },
  {
    id: "tx-015",
    date: "2025-08-27",
    description: "Transf Pix enviada",
    customerId: "067.164.483-14",
    customer: "JULIO CESAR RODR…",
    history: "Pró-labore",
    typeId: 2,
    type: "Débito",
    amount: 1500.0,
    accountId: 83,
    bank: "cora"
  },
  {
    id: "tx-016",
    date: "2025-08-29",
    description: "Compra no débito",
    customerId: "",
    customer: "POSTO CATATAU VII",
    history: "Combustível",
    typeId: 2,
    type: "Débito",
    amount: 150.0,
    accountId: 33,
    bank: "cora"
  },
  {
    id: "tx-018",
    date: "2025-08-30",
    description: "Compra no débito",
    customerId: "",
    customer: "SMILICOPY GRAFIVA",
    history: "Impressão de Fotos",
    typeId: 3,
    type: "Débito",
    amount: 5.0,
    accountId: 101,
    bank: "cora"
  },
  {
    id: "tx-019",
    date: "2025-08-30",
    description: "Compra no débito",
    customerId: "",
    customer: "AMERICANAS SA",
    history: "Pen Drive",
    typeId: 3,
    type: "Débito",
    amount: 89.97,
    accountId: 101,
    bank: "cora"
  },
  {
    id: "tx-020",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "067.164.483-14",
    customer: "JULIO CESAR RODR…",
    history: "Pró-labore",
    typeId: 2,
    type: "Débito",
    amount: 2793.06,
    accountId: 83,
    bank: "cora"
  },
  {
    id: "tx-021",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "082.939.493-17",
    customer: "JOAO VITOR FONT…",
    history: "Salários",
    typeId: 3,
    type: "Débito",
    amount: 1650.0,
    accountId: 18,
    bank: "cora"
  },
  {
    id: "tx-022",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "603.804.323-31",
    customer: "Mayane Lima dos Sa…",
    history: "Salários",
    typeId: 3,
    type: "Débito",
    amount: 1800.0,
    accountId: 18,
    bank: "cora"
  },
  {
    id: "tx-023",
    date: "2025-09-01",
    description: "Compra no débito",
    customerId: "603.804.323-31",
    customer: "LIPI SUPERMERCADO",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 4.69,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-024",
    date: "2025-09-01",
    description: "Pgto QR Code Pix",
    customerId: "00.394.460/0058-87",
    customer: "MINISTERIO DA FAZ…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 84.92,
    accountId: 89,
    bank: "cora"
  },
  {
    id: "tx-025",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "067.164.483-14",
    customer: "JULIO CESAR RODR…",
    history: "Pró-labore",
    typeId: 2,
    type: "Débito",
    amount: 50.0,
    accountId: 83,
    bank: "cora"
  },
  {
    id: "tx-026",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "063.536.963-02",
    customer: "JANAINA ALBUQUE…",
    history: "Esporádico",
    typeId: 1,
    type: "Crédito",
    amount: 3000.0,
    accountId: 2,
    bank: "cora"
  },
  {
    id: "tx-027",
    date: "2025-09-01",
    description: "Transf Pix enviada",
    customerId: "992.561.775-87",
    customer: "DANILA C M CERQU…",
    history: "Esporádico",
    typeId: 1,
    type: "Crédito",
    amount: 2000.0,
    accountId: 2,
    bank: "cora"
  },
  {
    id: "tx-028",
    date: "2025-09-02",
    description: "Transf Pix enviada",
    customerId: "083.039.283-17",
    customer: "Saimon Nascimento …",
    history: "Salários",
    typeId: 3,
    type: "Débito",
    amount: 950.0,
    accountId: 16,
    bank: "cora"
  },
  {
    id: "tx-029",
    date: "2025-09-02",
    description: "Transf Pix enviada",
    customerId: "638.844.613-20",
    customer: "ANA VLADIA MOREI…",
    history: "Esporádico",
    typeId: 1,
    type: "Crédito",
    amount: 2400.0,
    accountId: 2,
    bank: "cora"
  },
  {
    id: "tx-030",
    date: "2025-09-02",
    description: "Pgto QR Code Pix",
    customerId: "00.394.460/0058-87",
    customer: "MINISTERIO DA FAZ…",
    history: "Esporádico",
    typeId: 2,
    type: "Débito",
    amount: 80.90,
    accountId: 89,
    bank: "cora"
  },
  {
    id: "tx-031",
    date: "2025-09-07",
    description: "Compra no débito",
    customerId: "",
    customer: "POSTO CATATAU II",
    history: "Combustiveis",
    typeId: 2,
    type: "Débito",
    amount: 100.0,
    accountId: 33,
    bank: "cora"
  },
  {
    id: "tx-032",
    date: "2025-09-08",
    description: "Transf Pix enviada",
    customerId: "082.939.493-17",
    customer: "JOAO VITOR FONT…",
    history: "Comissões",
    typeId: 3,
    type: "Débito",
    amount: 150.0,
    accountId: 15,
    bank: "cora"
  },
  {
    id: "tx-033",
    date: "2025-09-08",
    description: "Transf Pix enviada",
    customerId: "082.939.493-17",
    customer: "Saimon Nascimento …",
    history: "Comissões",
    typeId: 3,
    type: "Débito",
    amount: 150.0,
    accountId: 15,
    bank: "cora"
  },
  {
    id: "tx-034",
    date: "2025-08-25",
    description: "Cobrança recebida",
    customerId: "05.356.440/0001-08",
    customer: "JLanches",
    history: "",
    typeId: 1,
    type: "Crédito",
    amount: 2500.0,
    accountId: 3,
    bank: "Asaas"
  },
  {
    id: "tx-035",
    date: "2025-08-25",
    description: "Taxa de boleto",
    customerId: "05.356.440/0001-08",
    customer: "JLanches",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 92,
    bank: "Asaas"
  },
  {
    id: "tx-036",
    date: "2025-08-25",
    description: "Taxa de mensageria",
    customerId: "05.356.440/0001-08",
    customer: "JLanches",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 81,
    bank: "Asaas"
  },
  {
    id: "tx-037",
    date: "2025-08-26",
    description: "Taxa de boleto",
    customerId: "26.158.183/0001-04",
    customer: "Perolab",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 92,
    bank: "Asaas"
  },
  {
    id: "tx-038",
    date: "2025-08-26",
    description: "Taxa de mensageria",
    customerId: "26.158.183/0001-04",
    customer: "Perolab",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 81,
    bank: "Asaas"
  },
  {
    id: "tx-039",
    date: "2025-08-26",
    description: "Cobrança recebida",
    customerId: "26.158.183/0001-04",
    customer: "Perolab",
    history: "",
    typeId: 1,
    type: "Crédito",
    amount: 2300.0,
    accountId: 3,
    bank: "Asaas"
  },
  {
    id: "tx-040",
    date: "2025-08-25",
    description: "Transação via Pix",
    customerId: "41.655.312/0001-10",
    customer: "Julio Cesar Rodrigues Pires",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 2500.0,
    accountId: 104,
    bank: "Asaas"
  },
  {
    id: "tx-041",
    date: "2025-08-26",
    description: "Transação via Pix",
    customerId: "41.655.312/0001-10",
    customer: "Julio Cesar Rodrigues Pires",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 2299.0,
    accountId: 104,
    bank: "Asaas"
  },
  {
    id: "tx-041",
    date: "2025-09-17",
    description: "Transação via Pix",
    customerId: "41.655.312/0001-10",
    customer: "Julio Cesar Rodrigues Pires",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 1998.12,
    accountId: 104,
    bank: "Asaas"
  },
  {
    id: "tx-042",
    date: "2025-09-15",
    description: "Cobrança recebida",
    customerId: "54.687.930/0001-94",
    customer: "FarmaFormula",
    history: "",
    typeId: 1,
    type: "Crédito",
    amount: 2000.0,
    accountId: 3,
    bank: "Asaas"
  },
  {
    id: "tx-043",
    date: "2025-09-15",
    description: "Taxa de boleto",
    customerId: "54.687.930/0001-94",
    customer: "FarmaFormula",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 92,
    bank: "Asaas"
  },
  {
    id: "tx-044",
    date: "2025-09-15",
    description: "Taxa de mensageria",
    customerId: "54.687.930/0001-94",
    customer: "FarmaFormula",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 0.99,
    accountId: 81,
    bank: "asaas"
  },
  {
    id: "tx-045",
    date: "2025-08-26",
    description: "Pgto QR Code Pix",
    customerId: "005.929.373-05",
    customer: "FABRICIO RODRIGU…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 12.0,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-046",
    date: "2025-08-27",
    description: "Pgto QR Code Pix",
    customerId: "02.268.603/0001-02",
    customer: "R G MOREIRA SOUZ…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 5.69,
    accountId: 102,
    bank: "cora"
  },
  {
    id: "tx-047",
    date: "2025-08-27",
    description: "Pgto QR Code Pix",
    customerId: "05.526.674/0001-48",
    customer: "TEIXEIRA SACOLAS",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 4.90,
    accountId: 74,
    bank: "cora"
  },
  {
    id: "tx-048",
    date: "2025-08-27",
    description: "Pgto QR Code Pix",
    customerId: "02.268.603/0001-02",
    customer: "R G MOREIRA SOUZ",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 13.49,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-049",
    date: "2025-08-27",
    description: "Pgto QR Code Pix",
    customerId: "11.889.648/0001-87",
    customer: "FRANCISCO JOSE D…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 6.50,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-050",
    date: "2025-08-29",
    description: "Compra no débito",
    customerId: "",
    customer: "DENNYSCELL UBAJ…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 20.0,
    accountId: 44,
    bank: "cora"
  },
  {
    id: "tx-051",
    date: "2025-08-29",
    description: "Compra no débito",
    customerId: "",
    customer: "FRANCISCO JOSE D…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 51.0,
    accountId: 31,
    bank: "cora"
  },
  {
    id: "tx-052",
    date: "2025-08-30",
    description: "Compra no débito",
    customerId: "",
    customer: "CACAU SHOW",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 15.99,
    accountId: 31,
    bank: "cora"
  },
  {
    id: "tx-059",
    date: "2025-08-30",
    description: "Compra no débito",
    customerId: "",
    customer: "MP*DAFFCE",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 56.40,
    accountId: 31,
    bank: "cora"
  },
  {
    id: "tx-053",
    date: "2025-09-05",
    description: "Compra no débito",
    customerId: "",
    customer: "MERCADINHO BOM…",
    history: "",
    typeId: 2,
    type: "Débito",
    amount: 5.58,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-054",
    date: "2025-09-08",
    description: "Compra no débito",
    customerId: "",
    customer: "MP*CHEFDOACAI",
    history: "Pró-labore",
    typeId: 2,
    type: "Débito",
    amount: 13.12,
    accountId: 103,
    bank: "cora"
  },
  {
    id: "tx-055",
    date: "2025-09-08",
    description: "Transf Pix enviada",
    customerId: "834.079.953-34",
    customer: "ANA CRISTINA PINT…",
    history: "Pró-labore",
    typeId: 2,
    type: "Débito",
    amount: 8.0,
    accountId: 65,
    bank: "cora"
  },
  {
    id: "tx-056",
    date: "2025-09-10",
    description: "Transf Pix enviada",
    customerId: "41.655.312/0001-10",
    customer: "41 655 312 JULIO C…",
    history: "Transferências",
    typeId: 2,
    type: "Débito",
    amount: 30.0,
    accountId: 104,
    bank: "cora"
  },
  {
    id: "tx-057",
    date: "2025-09-10",
    description: "Transf Pix enviada",
    customerId: "41.655.312/0001-10",
    customer: "41 655 312 JULIO C…",
    history: "Transferências",
    typeId: 2,
    type: "Débito",
    amount: 30.0,
    accountId: 104,
    bank: "cora"
  },
  {
    id: "tx-058",
    date: "2025-09-10",
    description: "Transf Pix enviada",
    customerId: "41.655.312/0001-10",
    customer: "41 655 312 JULIO C…",
    history: "Transferências",
    typeId: 2,
    type: "Débito",
    amount: 30.0,
    accountId: 104,
    bank: "cora"
  },
];

// export const mockCategories: MockCategoriesType[] = createMockCategories(mockTransactions);

export const mockMonthly: MockMonthlyType[] = createMockMonthly(mockTransactions);

export const chartAccounts: ChartAccountsType[] = [
  { id: 1, type: "Receitas", subcategories: [
    { accountId: 2, categories: "Projetos Avulsos", subordinate: "Receitas Variáveis" },
    { accountId: 3, categories: "Contratos Mensais", subordinate: "Receita Fixo" },
    { accountId: 4, categories: "Resgate de Aplicação", subordinate: "Retorno de Capital" },
    { accountId: 5, categories: "Juros e Multas", subordinate: "Outras Receitas" },  
  ] },
  { id: 2, type: "Despesas", subcategories: [
    { accountId: 1, categories: "Adiantamento de Salário", subordinate:	"Despesas Com Colaboradores" },
    { accountId: 6, categories:	"Agua", subordinate: "Despesas Administrativas" },
    { accountId: 7, categories: "Alugueis", subordinate: "Despesas Administrativas" },
    { accountId: 8,	categories: "Aplicações", subordinate: "Investimentos" },
    { accountId: 9, categories:	"Ativo Imobilizado", subordinate: "" },
    { accountId: 10, categories: "Beneficios Não Obrigatorios", subordinate: "Despesas Com Colaboradores" },
    { accountId: 12, categories: "Bonus por Metas", subordinate: "Despesas Com Colaboradores" },
    { accountId: 13, categories: "Brindes", subordinate: "Eventos e Confraternizações" },
    { accountId: 14, categories: "Comissão dos Colaboradores", subordinate: "Despesas Com Colaboradores" },
    { accountId: 17, categories: "Bolsa Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 19, categories: "Folha de Pagamento", subordinate: "Despesas Com Colaboradores" },
    { accountId: 20, categories: "Compras", subordinate: "" },
    { accountId: 21, categories: "Compras Esporádicas", subordinate: "Despesas Administrativas" },
    { accountId: 22, categories: "Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 23, categories: "Construções/Reformas", subordinate: "Despesas Administrativas" },
    { accountId: 24, categories: "Consultorias", subordinate: "Despesas Administrativas" },
    { accountId: 27, categories: "DAS Simples Nacional", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 29, categories: "Decimo Terceiro Salario", subordinate: "Despesas Com Colaboradores" },
    { accountId: 30, categories: "Despesas Administrativas", subordinate: "" },
    { accountId: 31, categories: "Despesas Com Clientes", subordinate: "Despesas Administrativas" },
    { accountId: 32, categories: "Despesas Com Colaboradores", subordinate: "" },
    { accountId: 33, categories: "Despesas Com Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 34, categories: "Despesas Com Viagens e Hospedagens", subordinate: "Despesas Administrativas" },
    { accountId: 35, categories: "Despesas de Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 36, categories: "Despesas Eventuais", subordinate: "" },
    { accountId: 37, categories: "Despesas Operacionais", subordinate: "" },
    { accountId: 38, categories: "Devoluções", subordinate: "Outras Despesas" },
    { accountId: 39, categories: "Emprestimos", subordinate: "Emprestimos e Financiamentos" },
    { accountId: 40, categories: "Emprestimos e Financiamentos", subordinate: "" },
    { accountId: 41, categories: "Emprestimos Internos", subordinate: "Outras Despesas" },
    { accountId: 42, categories: "Encargos Bancários", subordinate: "" },
    { accountId: 43, categories: "Energia", subordinate: "Despesas Administrativas" },
    { accountId: 44, categories: "Equip. Uso e Consumo", subordinate: "Despesas Administrativas" },
    { accountId: 45, categories: "Eventos e Confraternizações", subordinate: "" },
    { accountId: 48, categories: "Férias", subordinate: "Despesas Com Colaboradores" },
    { accountId: 52, categories: "Impostos", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 53, categories: "Impostos Mensais e Trimestrais", subordinate: "" },
    { accountId: 56, categories: "Integralização de Capital", subordinate: "Investimentos" },
    { accountId: 57, categories: "Internet", subordinate: "Despesas Administrativas" },
    { accountId: 58, categories: "Investimentos", subordinate: "" },
    { accountId: 59, categories: "IPTU", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 60, categories: "IPVA", subordinate: "Despesas Administrativas" },
    { accountId: 61, categories: "Jantares/Almoços Em Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 62, categories: "Juros de Emprestimos", subordinate: "Emprestimos e Financiamentos" },
    { accountId: 63, categories: "Juros e Multas", subordinate: "Despesas Administrativas" },
    { accountId: 64, categories: "Juros Utiliz Ch Especial", subordinate: "Encargos Bancários" },
    { accountId: 65, categories: "Lanches e Refeições", subordinate: "Despesas Com Colaboradores" },
    { accountId: 66, categories: "Lembranças e Troféus", subordinate: "Eventos e Confraternizações" },
    { accountId: 67, categories: "Manutençao da Conta", subordinate: "Encargos Bancários" },
    { accountId: 68, categories: "Manutenção de Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 69, categories: "Manutenção de Informatica", subordinate: "Despesas Administrativas" },
    { accountId: 70, categories: "Manutenção de Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 71, categories: "Manutenção Interna (máquinas, Luzes...)", subordinate: "Despesas Administrativas" },
    { accountId: 72, categories: "Manutenção Predial", subordinate: "Despesas Administrativas" },
    { accountId: 73, categories: "Maquinas e Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 74, categories: "Materiais de Higiene e Limpeza", subordinate: "Despesas Administrativas" },
    { accountId: 75, categories: "Material de Escritório", subordinate: "Despesas Administrativas" },
    { accountId: 76, categories: "Material Gráfico", subordinate: "Despesas Administrativas" },
    { accountId: 77, categories: "Moveis e Utensilios", subordinate: "Despesas Administrativas" },
    { accountId: 79, categories: "Outras Despesas", subordinate: "" },
    { accountId: 80, categories: "Outras Despesas", subordinate: "Despesas Eventuais" },
    { accountId: 81, categories: "Outras Tarifas", subordinate: "Encargos Bancários" },
    { accountId: 84, categories: "Rescisões", subordinate: "Despesas Com Colaboradores" },
    { accountId: 86, categories: "Seguros", subordinate: "Despesas Administrativas" },
    { accountId: 87, categories: "Serviços Extraordinários", subordinate: "Eventos e Confraternizações" },
    { accountId: 88, categories: "Serviços Terceirizados", subordinate: "Despesas Administrativas" },
    { accountId: 89, categories: "Simples Nacional", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 90, categories: "Sistemas Contratados", subordinate: "Despesas Administrativas" },
    { accountId: 91, categories: "Tarifas Bancárias", subordinate: "Encargos Bancários" },
    { accountId: 92, categories: "Tarifas de Boletos", subordinate: "Encargos Bancários" },
    { accountId: 93, categories: "Tarifas Pix", subordinate: "Encargos Bancários" },
    { accountId: 94, categories: "Tarifas Utiliz. Ch. Esp", subordinate: "Encargos Bancários" },
    { accountId: 95, categories: "Telefonia e Planos", subordinate: "Despesas Administrativas" },
    { accountId: 96, categories: "Terrenos e Imoveis", subordinate: "Despesas Administrativas" },
    { accountId: 97, categories: "Transferencias", subordinate: "" },
    { accountId: 98, categories: "Treinamentos e Cursos", subordinate: "Despesas Administrativas" },
    { accountId: 99, categories: "Uniformes e Crachás", subordinate: "Despesas Com Colaboradores" },
    { accountId: 100, categories: "Vale Transportes", subordinate: "Despesas Com Colaboradores" },
  ] },
  { id: 3, type: "Custos", subcategories: [
    { accountId: 11, categories: "Benefícios", subordinate: "Custo" },
    { accountId: 15, categories: "Comissões", subordinate: "Custo" },
    { accountId: 16, categories: "Bolsa Estágio", subordinate: "Custo" },
    { accountId: 18, categories: "Folha de Pagamento", subordinate: "Custo" },
    { accountId: 25, categories: "Custo com Sistemas", subordinate: "Custo" },
    { accountId: 26, categories: "Custos", subordinate: "" },
    { accountId: 28, categories: "Décimo Terceiro", subordinate: "Custo" },
    { accountId: 101, categories: "Entregas ao Cliente", subordinate: "Custo" },
    { accountId: 46, categories: "Exames ASO", subordinate: "Custo" },
    { accountId: 47, categories: "Férias", subordinate: "Custo" },
    { accountId: 49, categories: "FGTS", subordinate: "Custo" },
    { accountId: 50, categories: "FGTS Rescisório", subordinate: "Custo" },
    { accountId: 51, categories: "Horas Extras", subordinate: "Custo" },
    { accountId: 54, categories: "INSS", subordinate: "Custo" },
    { accountId: 55, categories: "INSS/IRRF", subordinate: "Custo" },
    { accountId: 82, categories: "Pró-labore", subordinate: "Custo" },
    { accountId: 85, categories: "Rescisões", subordinate: "Custo" },
  ] },
];
