import {
  MockCustomers,
  MockMonthlyType,
  MockCategoriesType,
  MockTransactionsType,
} from "@/lib/types";

export const mockCustomers: MockCustomers[] = [
  {
    cnpj: "98.636.752/0001-63",
    companyName: "Empresa ABC LTDA.",
    fantasyName: "Empresa ABC",
    email: "contato@empresaabc.com.br",
    phone: "(11) 98888-7777",
    signedContract: "Contrato_ABC_2025.pdf",
    signedDate: "2025-01-10",
    dueDate: "2026-01-10",
    contractTime: "12 meses",
    contractStatus: "ativo",
    monthlyFee: 1500.0,
    terminationClause: "Rescisão com aviso prévio de 60 dias.",
    address: {
      street: "Rua das Flores",
      neighborhood: "Centro",
      number: "1200",
      zipCode: "01010-000",
      city: "São Paulo",
      state: "SP",
      country: "Brasil",
    },
  },
  {
    cnpj: "21.456.789/0001-44",
    companyName: "Tech Solutions ME",
    fantasyName: "Tech Soluções",
    email: "suporte@techsolucoes.com",
    phone: "(21) 97777-6666",
    signedContract: "Contrato_Tech_2023.pdf",
    signedDate: "2023-05-15",
    dueDate: "2024-05-15",
    contractTime: "12 meses",
    contractStatus: "vencido",
    monthlyFee: 800.0,
    terminationClause: "Rescisão com aviso prévio de 30 dias.",
    address: {
      street: "Av. Atlântica",
      neighborhood: "Copacabana",
      number: "505",
      zipCode: "22010-001",
      city: "Rio de Janeiro",
      state: "RJ",
      country: "Brasil",
    },
  },
  {
    cnpj: "35.987.654/0001-09",
    companyName: "Comercial Delta S.A.",
    fantasyName: "Delta Comércio",
    email: "delta@comercialdelta.com",
    phone: "(31) 96666-5555",
    signedContract: null,
    signedDate: null,
    dueDate: null,
    contractTime: null,
    contractStatus: "em análise",
    monthlyFee: 0,
    terminationClause: null,
    address: {
      street: "Rua Minas Gerais",
      neighborhood: "Funcionários",
      number: "320",
      zipCode: "30130-000",
      city: "Belo Horizonte",
      state: "MG",
      country: "Brasil",
    },
  },
  {
    cnpj: "12.345.678/0001-22",
    companyName: "Alpha Consultoria Ltda.",
    fantasyName: "Alpha Consult",
    email: "contato@alphaconsult.com",
    phone: "(41) 95555-4444",
    signedContract: "Contrato_Alpha_2024.pdf",
    signedDate: "2024-07-01",
    dueDate: "2025-07-01",
    contractTime: "12 meses",
    contractStatus: "ativo",
    monthlyFee: 2200.0,
    terminationClause: "Rescisão somente com multa proporcional.",
    address: {
      street: "Av. Sete de Setembro",
      neighborhood: "Centro",
      number: "150",
      zipCode: "80010-000",
      city: "Curitiba",
      state: "PR",
      country: "Brasil",
    },
  },
  {
    cnpj: "87.654.321/0001-55",
    companyName: "Logística Rápida S/A",
    fantasyName: "Rápida Log",
    email: "financeiro@rapidalog.com",
    phone: "(51) 94444-3333",
    signedContract: "Contrato_RapidaLog_2022.pdf",
    signedDate: "2022-02-20",
    dueDate: "2023-02-20",
    contractTime: "12 meses",
    contractStatus: "rescindido",
    monthlyFee: 3000.0,
    terminationClause: "Rescisão antecipada por descumprimento contratual.",
    address: {
      street: "Rua dos Andradas",
      neighborhood: "Centro Histórico",
      number: "890",
      zipCode: "90020-010",
      city: "Porto Alegre",
      state: "RS",
      country: "Brasil",
    },
  },
  {
    cnpj: "44.222.111/0001-88",
    companyName: "StartUp Inova ME",
    fantasyName: "InovaTech",
    email: "hello@inovatech.com",
    phone: "(85) 93333-2222",
    signedContract: "Contrato_Inova_2025.pdf",
    signedDate: "2025-03-01",
    dueDate: "2025-09-01",
    contractTime: "6 meses",
    contractStatus: "pendente",
    monthlyFee: 1200.0,
    terminationClause: "Cláusula em negociação.",
    address: {
      street: "Av. Beira Mar",
      neighborhood: "Meireles",
      number: "456",
      zipCode: "60165-121",
      city: "Fortaleza",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "77.888.999/0001-33",
    companyName: "Agro Vale do Sol LTDA.",
    fantasyName: "Vale do Sol Agro",
    email: "agro@valedosol.com",
    phone: "(62) 92222-1111",
    signedContract: "Contrato_Vale_2024.pdf",
    signedDate: "2024-09-15",
    dueDate: "2025-09-15",
    contractTime: "12 meses",
    contractStatus: "em renovação",
    monthlyFee: 5000.0,
    terminationClause: "Rescisão com aviso de 90 dias.",
    address: {
      street: "Rodovia BR-153",
      neighborhood: "Zona Rural",
      number: "Km 45",
      zipCode: "74000-000",
      city: "Goiânia",
      state: "GO",
      country: "Brasil",
    },
  },
];

export const mockMonthly: MockMonthlyType[] = [
	{
		month: "Ago",
    date: "2025-08-01",
		fixedRevenue: 2875.99,
		fixedExpense: 3528.53,
		variableRevenue: 2749.54,
		variableExpenses: 1736.63
	},
	{
		month: "Set",
    date: "2025-09-01",
		fixedRevenue: 3000,
		fixedExpense: 2800,
		variableRevenue: 2568.89,
		variableExpenses: 1897.57
	},
	{
		month: "Out",
    date: "2025-10-01",
		fixedRevenue: 3000,
		fixedExpense: 2800,
		variableRevenue: 3128.45,
		variableExpenses: 2341.12
	},
	{
		month: "Nov",
    date: "2025-11-01",
		fixedRevenue: 3000,
		fixedExpense: 2800,
		variableRevenue: 1544.67,
		variableExpenses: 2027.34
	},
	{
		month: "Dez",
    date: "2025-12-01",
		fixedRevenue: 3000,
		fixedExpense: 2800,
		variableRevenue: 3000,
		variableExpenses: 2000
	},
];

export const mockCategories: MockCategoriesType[] = [
	{ name: "Folha", value: 38000 },
	{ name: "Infraestrutura", value: 12000 },
	{ name: "Marketing", value: 8000 },
	{ name: "Operacional", value: 15000 },
	{ name: "Impostos", value: 9000 },
];

export const mockTransactions: MockTransactionsType[] = [
  { id: "tx-001", date: "2025-08-01", description: "Assinatura SaaS", type: "Despesa", category: "Infraestrutura", amount: -1200.5, account: "Banco Principal" },
  { id: "tx-002", date: "2025-08-02", description: "Venda Plano Enterprise", type: "Receita", category: "Vendas", amount: 18000, account: "Banco Principal" },
  { id: "tx-003", date: "2025-08-03", description: "Campanha Ads", type: "Despesa", category: "Marketing", amount: -3500, account: "Cartão Corporativo" },
  { id: "tx-004", date: "2025-08-04", description: "Serviço de Consultoria", type: "Receita", category: "Serviços", amount: 9500, account: "Banco Secundário" },
  { id: "tx-005", date: "2025-08-05", description: "Impostos Federais", type: "Despesa", category: "Impostos", amount: -7000, account: "Banco Principal" },
  { id: "tx-006", date: "2025-08-06", description: "Assinatura Cloud Hosting", type: "Despesa", category: "Infraestrutura", amount: -2200, account: "Cartão Corporativo" },
  { id: "tx-007", date: "2025-08-06", description: "Pagamento Cliente Beta", type: "Receita", category: "Vendas", amount: 4500, account: "Banco Principal" },
  { id: "tx-008", date: "2025-08-07", description: "Treinamento de Equipe", type: "Despesa", category: "RH", amount: -1800, account: "Banco Secundário" },
  { id: "tx-009", date: "2025-08-08", description: "Venda Plano Premium", type: "Receita", category: "Vendas", amount: 7200, account: "Banco Principal" },
  { id: "tx-010", date: "2025-08-09", description: "Energia Elétrica Escritório", type: "Despesa", category: "Operacional", amount: -950, account: "Banco Principal" },
  { id: "tx-011", date: "2025-08-10", description: "Manutenção Servidores", type: "Despesa", category: "Infraestrutura", amount: -3100, account: "Cartão Corporativo" },
  { id: "tx-012", date: "2025-08-11", description: "Receita Parceria Estratégica", type: "Receita", category: "Parcerias", amount: 15000, account: "Banco Secundário" },
  { id: "tx-013", date: "2025-08-12", description: "Aluguel Escritório", type: "Despesa", category: "Operacional", amount: -8500, account: "Banco Principal" },
  { id: "tx-014", date: "2025-08-12", description: "Venda Customizada Cliente X", type: "Receita", category: "Serviços", amount: 12500, account: "Banco Principal" },
  { id: "tx-015", date: "2025-08-13", description: "Compra Equipamentos TI", type: "Despesa", category: "Infraestrutura", amount: -5600, account: "Banco Secundário" },
  { id: "tx-016", date: "2025-08-14", description: "Receita Workshop Online", type: "Receita", category: "Serviços", amount: 4200, account: "Banco Principal" },
  { id: "tx-017", date: "2025-08-15", description: "Marketing Influencer", type: "Despesa", category: "Marketing", amount: -2300, account: "Cartão Corporativo" },
  { id: "tx-018", date: "2025-08-16", description: "Venda Licença Software", type: "Receita", category: "Vendas", amount: 9800, account: "Banco Principal" },
  { id: "tx-019", date: "2025-08-17", description: "Alimentação Escritório", type: "Despesa", category: "Operacional", amount: -600, account: "Banco Secundário" },
  { id: "tx-020", date: "2025-08-18", description: "Pagamento Cliente Gamma", type: "Receita", category: "Vendas", amount: 5400, account: "Banco Principal" },
  { id: "tx-021", date: "2025-08-19", description: "Seguro Empresarial", type: "Despesa", category: "Operacional", amount: -2700, account: "Banco Principal" },
  { id: "tx-022", date: "2025-08-20", description: "Receita Programa Afiliados", type: "Receita", category: "Marketing", amount: 3100, account: "Banco Secundário" },
  { id: "tx-023", date: "2025-08-21", description: "Transporte Colaboradores", type: "Despesa", category: "RH", amount: -1250, account: "Cartão Corporativo" },
  { id: "tx-024", date: "2025-08-22", description: "Venda Consultoria Avançada", type: "Receita", category: "Serviços", amount: 13800, account: "Banco Principal" },
  { id: "tx-025", date: "2025-08-23", description: "Material de Escritório", type: "Despesa", category: "Operacional", amount: -750, account: "Banco Secundário" },
  { id: "tx-026", date: "2025-08-24", description: "Assinatura Plataforma Analytics", type: "Despesa", category: "Infraestrutura", amount: -1400, account: "Cartão Corporativo" },
  { id: "tx-027", date: "2025-08-25", description: "Receita Licenciamento API", type: "Receita", category: "Serviços", amount: 8900, account: "Banco Principal" },
  { id: "tx-028", date: "2025-08-26", description: "Consultoria Jurídica", type: "Despesa", category: "Serviços", amount: -3200, account: "Banco Secundário" },
  { id: "tx-029", date: "2025-08-27", description: "Venda Pacote Treinamento", type: "Receita", category: "Serviços", amount: 6700, account: "Banco Principal" },
  { id: "tx-030", date: "2025-08-28", description: "Infraestrutura Cloud Extra", type: "Despesa", category: "Infraestrutura", amount: -4100, account: "Cartão Corporativo" },
];
