import {
  MockCustomers,
  MockMonthlyType,
  MockFixedExpense,
  ChartAccountsType,
  MockTransactionsType,
} from "@/lib/types";

export const openingBalance = [
  { date: "2025-08-16", openingBalance: 0.0, bank: "Cora" },
  { date: "2025-08-24", openingBalance: 0.0, bank: "Asaas" }, 
  { date: "2025-08-16", openingBalance: 0.0, bank: "Santander" }
];

export const mockCustomers: MockCustomers[] = [
  {
    cnpj: "31.189.690/0001-00",
    companyName: "T. C DE SOUSA & CIA LTDA ",
    fantasyName: "Diamond",
    email: "tiangua@clinicasdiamond.com",
    phone: "(86) 9413-8179",
    signedContract: "",
    signedDate: "",
    dueDate: "2025-10-20",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 3000.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "1028",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "54.687.930/0001-94",
    companyName: "FRAGA E REZENDE LTDA",
    fantasyName: "Farmaformula",
    email: "lutrf1@gmail.com",
    phone: "(88) 9206-8076",
    signedContract: "",
    signedDate: "",
    dueDate: "2025-10-15",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 2000.0,
    terminationClause: "",
    address: {
      avenue: "",
      street: "Rua 31 de Julho",
      neighborhood: "Centro",
      number: "200",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  { 
    cnpj: "05.356.440/0001-08",
    companyName: "J B FERREIRA DE SA",
    fantasyName: "J. Lanches Pizzaria Delivery",
    email: "",
    phone: "(88) 3671-0000",
    signedContract: "",
    signedDate: "",
    dueDate: "2025-10-20",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 2500.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "2210",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "43.213.724/0001-08",
    companyName: "F OLIVER AGUIAR LOPES LTDA",
    fantasyName: "Casa de Cecília",
    email: "franzemlopes@hotmail.com",
    phone: "(88) 9717-6200",
    signedContract: "",
    signedDate: "",
    dueDate: "2025-10-20",
    contractTime: "",
    contractStatus: "ativo",
    monthlyFee: 3000.0,
    terminationClause: "",
    address: {
      avenue: "Av Prefeito Jaques Nunes",
      street: "",
      neighborhood: "Centro",
      number: "1048",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  },
  {
    cnpj: "26.158.183/0004-04",
    companyName: "KAROLYNE SIQUEIRA FREIRE LTDA",
    fantasyName: "Perolab",
    email: "otica_perola@hotmail.com",
    phone: "(88) 9344-7144",
    signedContract: "",
    signedDate: "",
    dueDate: "2025-09-26",
    contractTime: "",
    contractStatus: "suspenso",
    monthlyFee: 2300.0,
    terminationClause: "",
    address: {
      avenue: "",
      street: "R Maria do Socorro Frota e Fontenele",
      neighborhood: "Regis Diniz",
      number: "381",
      zipCode: "62320-000",
      city: "Tianguá",
      state: "CE",
      country: "Brasil",
    },
  }
];

export const mockExpensesFixed: MockFixedExpense[] = [
  {
    description: "João Vitor",
    paymentMethod: "Transferência",
    amount: 1500.0,
    dueDate: "2025-10-01",
    observation: "Carteira assinada"
  },
  {
    description: "Saymon",
    paymentMethod: "Transferência",
    amount: 800.0,
    dueDate: "2025-10-01",
    observation: "Estagiário"
  },
  {
    description: "Mayane",
    paymentMethod: "Transferência",
    amount: 1500.0,
    dueDate: "2025-10-01",
    observation: "Sócio sem recolhimento"
  },
  {
    description: "Júlio César",
    paymentMethod: "Transferência",
    amount: 4000.0,
    dueDate: "2025-10-01",
    observation: "Sócio sem recolhimento"
  },
  {
    description: "INSS",
    paymentMethod: "Guia",
    amount: 0.0,
    dueDate: "2025-09-20",
    observation: "Encargo CLT"
  },
  {
    description: "FGTS",
    paymentMethod: "Guia",
    amount: 0.0,
    dueDate: "2025-09-01",
    observation: "Encargo CLT"
  },
  {
    description: "Seguro",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Encargo estagiário"
  },
  {
    description: "Agência",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Encargo estagiário"
  },
  {
    description: "Provisão 13º",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Provisão mensal CLT"
  },
  {
    description: "Provisão Féria",
    paymentMethod: "",
    amount: 0.0,
    dueDate: "",
    observation: "Provisão mensal CLT"
  },
  {
    description: "Internet",
    paymentMethod: "Boleto",
    amount: 92.17,
    dueDate: "2025-10-10",
    observation: ""
  },
  {
    description: "Aluguel + Energia",
    paymentMethod: "Desconto",
    amount: 700.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Software - Adobe (cartão hype)",
    paymentMethod: "Cartão",
    amount: 92.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Software - Google",
    paymentMethod: "Cartão",
    amount: 105.0,
    dueDate: "2025-10-20",
    observation: ""
  },
  {
    description: "Tripé",
    paymentMethod: "Cartão",
    amount: 49.44,
    dueDate: "2025-10-20",
    observation: "18x (2/18) - Finaliza (12/2026)"
  },
  {
    description: "Treinamento Don",
    paymentMethod: "Cartão",
    amount: 149.44,
    dueDate: "2025-10-20",
    observation: "12x (2/12) - Finaliza (06/2026)"
  },
  {
    description: "DAF/Gaveteiros",
    paymentMethod: "Cartão",
    amount: 66.93,
    dueDate: "2025-10-20",
    observation: "3x (2/3) - Finaliza (09/2025)"
  },
  {
    description: "Ar-condicionado",
    paymentMethod: "Cartão",
    amount: 291.83,
    dueDate: "2025-10-20",
    observation: "10x (8/10) - Finaliza (10/2025)"
  },
  {
    description: "Mensalidade BPO",
    paymentMethod: "Boleto",
    amount: 300.0,
    dueDate: "2025-10-25",
    observation: "A partir de setembro"
  },
  {
    description: "Mensalidade Contabilidade",
    paymentMethod: "Boleto",
    amount: 80.0,
    dueDate: "2025-10-25",
    observation: "Após alteração"
  },
  {
    description: "Simples Nacional",
    paymentMethod: "Guia",
    amount: 600.0,
    dueDate: "2025-10-20",
    observation: "6% do faturamento"
  },
  {
    description: "Processo de alteração contábil",
    paymentMethod: "Transferência",
    amount: 1000.0,
    dueDate: "A definir",
    observation: "Apenas uma vez"
  },
  {
    description: "Taxa de processo JUCEC",
    paymentMethod: "Boleto",
    amount: 260.0,
    dueDate: "",
    observation: "Apenas quando iniciar o processo"
  },
  {
    description: "Débitos antigos MEI",
    paymentMethod: "Guia",
    amount: 1236.08,
    dueDate: "",
    observation: "309.02/mês (4x)"
  },
  {
    description: "MEI 2025",
    paymentMethod: "Guia",
    amount: 471.17,
    dueDate: "",
    observation: "Em aberto para 2025"
  },
];

function createMockMonthly(data: MockTransactionsType[]) {
  const monthName = [
    { name: 'Jan', number: 0 },
    { name: 'Fev', number: 1 }, 
    { name: 'Mar', number: 2 }, 
    { name: 'Abr', number: 3 },
    { name: 'Mai', number: 4 },
    { name: 'Jun', number: 5 },
    { name: 'Jul', number: 6 },
    { name: 'Ago', number: 7 },
    { name: 'Set', number: 8 }, 
    { name: 'Out', number: 9 },
    { name: 'Nov', number: 10 },
    { name: 'Dez', number: 11 }
  ];
  
  const result: MockMonthlyType[] = [];

  const dates = data.map((item) => new Date(item.date)).sort((a, b) => a.getTime() - b.getTime());
  const minDate = dates[0];
  const maxDate = dates[dates.length - 1];

  // const fixedCount = data.reduce((accumulator, currentValue) => {
  //   return currentValue.accountId === 3 ? accumulator + 1 : accumulator;
  // }, 0);

  // const eventCount = data.reduce((accumulator, currentValue) => {
  //   return currentValue.accountId === 2 ? accumulator + 1 : accumulator;
  // }, 0);
  
  for (let i = minDate.getMonth(); i <= maxDate.getMonth(); i++) {
    const filtered = data.filter((register) => new Date(register.date).getMonth() === i);

    const variableRevenue = filtered
      .filter((register) => register.typeId === 1 && register.accountId === 2)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const fixedRevenue = filtered
      .filter((register) => register.typeId === 1 && register.accountId === 3)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const cost = filtered
      .filter((register) => register.typeId === 3)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);
    const expense = filtered
      .filter((register) => register.typeId === 2 && register.accountId !== 104)
      .reduce((accumulator, currentValue) => accumulator + currentValue.amount, 0);

    result.push({ 
      month: monthName[i].name, 
      date: `2025-${String(i+1).padStart(2, "0")}-01`, 
      fixedRevenue, 
      variableRevenue,
      expense,
      cost,
    });
  }
  
  const averageOrderValueFixed = result.reduce((acc, cur) => acc + cur.fixedRevenue, 0) / 5;
  const averageOrderValueEvent = result.reduce((acc, cur) => acc + cur.variableRevenue, 0) / 4;

  return { month: result, averageOrderValueFixed, averageOrderValueEvent };
}

export const mockTransactions: MockTransactionsType[] = [
  {
    "id": "tx-0001",
    "date": "2025-08-22",
    "description": "Transf Pix recebida",
    "history": "Mensalidade",
    "customerId": "43.213.742/0001-08",
    "customer": "Casa de Cecília",
    "typeId": 1,
    "type": "Credito",
    "amount": 3000.0,
    "accountId": 3,
    "bank": "Cora"
  },
  {
    "id": "tx-0002",
    "date": "2025-08-22",
    "description": "Transf Pix recebida",
    "history": "Mensalidade",
    "customerId": "31.189.690/0001-00",
    "customer": "Diamond",
    "typeId": 1,
    "type": "Credito",
    "amount": 1000.0,
    "accountId": 3,
    "bank": "Cora"
  },
  {
    "id": "tx-0003",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Gaveteiros",
    "customerId": "10.573.521/0001-92",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 66.93,
    "accountId": 77,
    "bank": "Cora"
  },
  {
    "id": "tx-0004",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Ar Condicionado",
    "customerId": "10.573.521/0001-93",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 291.83,
    "accountId": 73,
    "bank": "Cora"
  },
  {
    "id": "tx-0005",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Tripé",
    "customerId": "10.573.521/0001-94",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 49.44,
    "accountId": 73,
    "bank": "Cora"
  },
  {
    "id": "tx-0006",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Trieinamento",
    "customerId": "10.573.521/0001-95",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 149.7,
    "accountId": 98,
    "bank": "Cora"
  },
  {
    "id": "tx-0007",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Programa de Edição",
    "customerId": "10.573.521/0001-96",
    "customer": "MERCADO PAGO IN…",
    "typeId": 3,
    "type": "Debito",
    "amount": 95.0,
    "accountId": 25,
    "bank": "Cora"
  },
  {
    "id": "tx-0008",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Sistemas Contratados",
    "customerId": "10.573.521/0001-97",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 27.95,
    "accountId": 90,
    "bank": "Cora"
  },
  {
    "id": "tx-0009",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Sistemas Contratados",
    "customerId": "10.573.521/0001-98",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 24.47,
    "accountId": 90,
    "bank": "Cora"
  },
  {
    "id": "tx-0010",
    "date": "2025-08-23",
    "description": "Pgto QR Code Pix",
    "history": "Sistemas Contratados",
    "customerId": "10.573.521/0001-99",
    "customer": "MERCADO PAGO IN…",
    "typeId": 2,
    "type": "Debito",
    "amount": 324.22,
    "accountId": 90,
    "bank": "Cora"
  },
  {
    "id": "tx-0011",
    "date": "2025-08-25",
    "description": "Transf Pix recebida",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41.655.312 JULIO C…",
    "typeId": 1,
    "type": "Credito",
    "amount": 2500.0,
    "accountId": 106,
    "bank": "Cora"
  },
  {
    "id": "tx-0012",
    "date": "2025-08-26",
    "description": "Transf Pix recebida",
    "history": "Mensalidade",
    "customerId": "31.189.690/0001-00",
    "customer": "Diamond",
    "typeId": 1,
    "type": "Credito",
    "amount": 1000.0,
    "accountId": 3,
    "bank": "Cora"
  },
  {
    "id": "tx-0013",
    "date": "2025-08-26",
    "description": "Pgto QR Code Pix",
    "history": "Lanches para colaboradores",
    "customerId": "005.929.373-05",
    "customer": "FABRICIO RODRIGU…",
    "typeId": 2,
    "type": "Debito",
    "amount": 12.0,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0014",
    "date": "2025-08-26",
    "description": "Transf Pix recebida",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41.655.312 JULIO C…",
    "typeId": 1,
    "type": "Credito",
    "amount": 2299.0,
    "accountId": 106,
    "bank": "Cora"
  },
  {
    "id": "tx-0015",
    "date": "2025-08-27",
    "description": "Pgto QR Code Pix",
    "history": "Coador de café",
    "customerId": "02.268.603/0001-02",
    "customer": "R G MOREIRA SOUZ…",
    "typeId": 2,
    "type": "Debito",
    "amount": 5.69,
    "accountId": 102,
    "bank": "Cora"
  },
  {
    "id": "tx-0016",
    "date": "2025-08-27",
    "description": "Pgto QR Code Pix",
    "history": "Copos descartaveis",
    "customerId": "05.526.674/0001-48",
    "customer": "TEIXEIRA SACOLAS",
    "typeId": 2,
    "type": "Debito",
    "amount": 4.9,
    "accountId": 74,
    "bank": "Cora"
  },
  {
    "id": "tx-0017",
    "date": "2025-08-27",
    "description": "Pgto QR Code Pix",
    "history": "Lanches para colaboradores",
    "customerId": "02.268.603/0001-02",
    "customer": "R G MOREIRA SOUZ",
    "typeId": 2,
    "type": "Debito",
    "amount": 13.49,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0018",
    "date": "2025-08-27",
    "description": "Pgto QR Code Pix",
    "history": "Lanches para colaboradores",
    "customerId": "11.889.648/0001-87",
    "customer": "FRANCISCO JOSE D…",
    "typeId": 2,
    "type": "Debito",
    "amount": 6.5,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0019",
    "date": "2025-08-27",
    "description": "Transf Pix enviada",
    "history": "Pró-labore",
    "customerId": "067.164.483-14",
    "customer": "JULIO CESAR RODR…",
    "typeId": 3,
    "type": "Debito",
    "amount": 1500.0,
    "accountId": 103,
    "bank": "Cora"
  },
  {
    "id": "tx-0020",
    "date": "2025-08-28",
    "description": "Transf Pix recebida",
    "history": "Mensalidade",
    "customerId": "26.719.797/0001-75",
    "customer": "Diamond",
    "typeId": 1,
    "type": "Credito",
    "amount": 1000.0,
    "accountId": 3,
    "bank": "Cora"
  },
  {
    "id": "tx-0021",
    "date": "2025-08-29",
    "description": "Compra no débito",
    "history": "Combustiveis",
    "customerId": "nan",
    "customer": "POSTO CATATAU VII",
    "typeId": 2,
    "type": "Debito",
    "amount": 150.0,
    "accountId": 33,
    "bank": "Cora"
  },
  {
    "id": "tx-0022",
    "date": "2025-08-29",
    "description": "Compra no débito",
    "history": "Cabo tipo-c",
    "customerId": "nan",
    "customer": "DENNYSCELL UBAJ…",
    "typeId": 2,
    "type": "Debito",
    "amount": 20.0,
    "accountId": 44,
    "bank": "Cora"
  },
  {
    "id": "tx-0023",
    "date": "2025-08-29",
    "description": "Compra no débito",
    "history": "Caixas para entrega final ao cliente",
    "customerId": "nan",
    "customer": "AliceArtefatosEm",
    "typeId": 2,
    "type": "Debito",
    "amount": 51.0,
    "accountId": 31,
    "bank": "Cora"
  },
  {
    "id": "tx-0024",
    "date": "2025-08-30",
    "description": "Compra no débito",
    "history": "Impressão de Fotos",
    "customerId": "nan",
    "customer": "SMILICOPY GRAFIVA",
    "typeId": 3,
    "type": "Debito",
    "amount": 5.0,
    "accountId": 101,
    "bank": "Cora"
  },
  {
    "id": "tx-0025",
    "date": "2025-08-30",
    "description": "Compra no débito",
    "history": "3 Pen Drives para entrega ao cliente",
    "customerId": "nan",
    "customer": "AMERICANAS SA",
    "typeId": 3,
    "type": "Debito",
    "amount": 89.97,
    "accountId": 101,
    "bank": "Cora"
  },
  {
    "id": "tx-0026",
    "date": "2025-08-30",
    "description": "Compra no débito",
    "history": "Chocolate para entrega final ao cliente",
    "customerId": "nan",
    "customer": "CACAU SHOW",
    "typeId": 2,
    "type": "Debito",
    "amount": 15.99,
    "accountId": 31,
    "bank": "Cora"
  },
  {
    "id": "tx-0027",
    "date": "2025-08-30",
    "description": "Compra no débito",
    "history": "Porta-retratos para entrega ao cliente",
    "customerId": "nan",
    "customer": "MP*DAFFCE",
    "typeId": 2,
    "type": "Debito",
    "amount": 56.4,
    "accountId": 31,
    "bank": "Cora"
  },
  {
    "id": "tx-0028",
    "date": "2025-09-01",
    "description": "Transf Pix enviada",
    "history": "Pró-labore",
    "customerId": "067.164.483-14",
    "customer": "JULIO CESAR RODR…",
    "typeId": 3,
    "type": "Debito",
    "amount": 2793.06,
    "accountId": 103,
    "bank": "Cora"
  },
  {
    "id": "tx-0029",
    "date": "2025-09-01",
    "description": "Transf Pix enviada",
    "history": "Salários",
    "customerId": "082.939.493-17",
    "customer": "JOAO VITOR FONT…",
    "typeId": 3,
    "type": "Debito",
    "amount": 1650.0,
    "accountId": 18,
    "bank": "Cora"
  },
  {
    "id": "tx-0030",
    "date": "2025-09-01",
    "description": "Transf Pix enviada",
    "history": "Salários",
    "customerId": "603.804.323-31",
    "customer": "Mayane Lima dos Sa…",
    "typeId": 3,
    "type": "Debito",
    "amount": 1800.0,
    "accountId": 18,
    "bank": "Cora"
  },
  {
    "id": "tx-0031",
    "date": "2025-09-01",
    "description": "Compra no débito",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "LIPI SUPERMERCADO",
    "typeId": 2,
    "type": "Debito",
    "amount": 4.69,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0032",
    "date": "2025-09-01",
    "description": "Pgto QR Code Pix",
    "history": "MEI atrasado",
    "customerId": "00.394.460/0058-87",
    "customer": "MINISTERIO DA FAZ…",
    "typeId": 2,
    "type": "Debito",
    "amount": 84.92,
    "accountId": 27,
    "bank": "Cora"
  },
  {
    "id": "tx-0033",
    "date": "2025-09-01",
    "description": "Transf Pix enviada",
    "history": "Pró-labore",
    "customerId": "067.164.483-14",
    "customer": "JULIO CESAR RODR…",
    "typeId": 3,
    "type": "Debito",
    "amount": 50.0,
    "accountId": 103,
    "bank": "Cora"
  },
  {
    "id": "tx-0034",
    "date": "2025-09-01",
    "description": "Transf Pix recebida",
    "history": "Esporádico",
    "customerId": "063.536.963-02",
    "customer": "JANAINA ALBUQUE…",
    "typeId": 1,
    "type": "Credito",
    "amount": 3000.0,
    "accountId": 2,
    "bank": "Cora"
  },
  {
    "id": "tx-0035",
    "date": "2025-09-01",
    "description": "Transf Pix recebida",
    "history": "Esporádico",
    "customerId": "992.561.775-87",
    "customer": "DANILA C M CERQU…",
    "typeId": 1,
    "type": "Credito",
    "amount": 2000.0,
    "accountId": 2,
    "bank": "Cora"
  },
  {
    "id": "tx-0036",
    "date": "2025-09-02",
    "description": "Transf Pix enviada",
    "history": "Salários",
    "customerId": "083.039.283-17",
    "customer": "Saimon Nascimento …",
    "typeId": 3,
    "type": "Debito",
    "amount": 950.0,
    "accountId": 16,
    "bank": "Cora"
  },
  {
    "id": "tx-0037",
    "date": "2025-09-02",
    "description": "Transf Pix recebida",
    "history": "Esporádico",
    "customerId": "638.844.613-20",
    "customer": "ANA VLADIA MOREI…",
    "typeId": 1,
    "type": "Credito",
    "amount": 2400.0,
    "accountId": 2,
    "bank": "Cora"
  },
  {
    "id": "tx-0038",
    "date": "2025-09-02",
    "description": "Pgto QR Code Pix",
    "history": "MEI mês atual",
    "customerId": "00.394.460/0058-87",
    "customer": "MINISTERIO DA FAZ…",
    "typeId": 2,
    "type": "Debito",
    "amount": 80.9,
    "accountId": 27,
    "bank": "Cora"
  },
  {
    "id": "tx-0039",
    "date": "2025-09-03",
    "description": "Transf Pix enviada",
    "history": "Locação de câmera",
    "customerId": "52.640.748/0001-52",
    "customer": "52.640.748 ANDRE …",
    "typeId": 2,
    "type": "Debito",
    "amount": 180.0,
    "accountId": 88,
    "bank": "Cora"
  },
  {
    "id": "tx-0040",
    "date": "2025-09-05",
    "description": "Compra no débito",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "MERCADINHO BOM…",
    "typeId": 2,
    "type": "Debito",
    "amount": 5.58,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0041",
    "date": "2025-09-07",
    "description": "Compra no débito",
    "history": "Combustiveis",
    "customerId": "nan",
    "customer": "POSTO CATATAU II",
    "typeId": 2,
    "type": "Debito",
    "amount": 100.0,
    "accountId": 33,
    "bank": "Cora"
  },
  {
    "id": "tx-0042",
    "date": "2025-09-08",
    "description": "Compra no débito",
    "history": "Pró-labore",
    "customerId": "nan",
    "customer": "MP*CHEFDOACAI",
    "typeId": 3,
    "type": "Debito",
    "amount": 13.12,
    "accountId": 103,
    "bank": "Cora"
  },
  {
    "id": "tx-0043",
    "date": "2025-09-08",
    "description": "Transf Pix enviada",
    "history": "Comissões",
    "customerId": "082.939.493-17",
    "customer": "JOAO VITOR FONT…",
    "typeId": 3,
    "type": "Debito",
    "amount": 150.0,
    "accountId": 15,
    "bank": "Cora"
  },
  {
    "id": "tx-0044",
    "date": "2025-09-08",
    "description": "Transf Pix enviada",
    "history": "Comissões",
    "customerId": "082.939.493-17",
    "customer": "Saimon Nascimento …",
    "typeId": 3,
    "type": "Debito",
    "amount": 150.0,
    "accountId": 15,
    "bank": "Cora"
  },
  {
    "id": "tx-0045",
    "date": "2025-09-08",
    "description": "Transf Pix enviada",
    "history": "Lanches para colaboradores",
    "customerId": "834.079.953-34",
    "customer": "ANA CRISTINA PINT…",
    "typeId": 2,
    "type": "Debito",
    "amount": 8.0,
    "accountId": 65,
    "bank": "Cora"
  },
  {
    "id": "tx-0046",
    "date": "2025-09-10",
    "description": "Transf Pix enviada",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41 655 312 JULIO C…",
    "typeId": 2,
    "type": "Debito",
    "amount": 30.0,
    "accountId": 104,
    "bank": "Cora"
  },
  {
    "id": "tx-0047",
    "date": "2025-09-10",
    "description": "Transf Pix enviada",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41 655 312 JULIO C…",
    "typeId": 2,
    "type": "Debito",
    "amount": 30.0,
    "accountId": 104,
    "bank": "Cora"
  },
  {
    "id": "tx-0048",
    "date": "2025-09-10",
    "description": "Transf Pix enviada",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41 655 312 JULIO C…",
    "typeId": 2,
    "type": "Debito",
    "amount": 30.0,
    "accountId": 104,
    "bank": "Cora"
  },
  {
    "id": "tx-0049",
    "date": "2025-09-11",
    "description": "Transf Pix enviada",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "41 655 312 JULIO C…",
    "typeId": 2,
    "type": "Debito",
    "amount": 7129.65,
    "accountId": 104,
    "bank": "Cora"
  },
  {
    "id": "tx-0050",
    "date": "2025-08-25",
    "description": "Cobrança recebida",
    "history": "Mensalidade",
    "customerId": "05.356.440/0001-08",
    "customer": "JLanches",
    "typeId": 1,
    "type": "Credito",
    "amount": 2500.0,
    "accountId": 3,
    "bank": "Asaas"
  },
  {
    "id": "tx-0051",
    "date": "2025-08-25",
    "description": "Taxa de boleto",
    "history": "Tarifas de boletos",
    "customerId": "05.356.440/0001-08",
    "customer": "JLanches",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 92,
    "bank": "Asaas"
  },
  {
    "id": "tx-0052",
    "date": "2025-08-25",
    "description": "Taxa de mensageria",
    "history": "Tarifas de mensageria",
    "customerId": "05.356.440/0001-08",
    "customer": "JLanches",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 81,
    "bank": "Asaas"
  },
  {
    "id": "tx-0053",
    "date": "2025-08-25",
    "description": "Transação via Pix",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "JULIO CESAR RODRIGUES PIRES",
    "typeId": 2,
    "type": "Debito",
    "amount": 2500.0,
    "accountId": 104,
    "bank": "Asaas"
  },
  {
    "id": "tx-0054",
    "date": "2025-08-26",
    "description": "Cobrança recebida",
    "history": "Mensalidades",
    "customerId": "26.158.183/0004-04",
    "customer": "Perolab",
    "typeId": 1,
    "type": "Credito",
    "amount": 2300.0,
    "accountId": 3,
    "bank": "Asaas"
  },
  {
    "id": "tx-0055",
    "date": "2025-08-26",
    "description": "Taxa de boleto",
    "history": "Tarifas de boletos",
    "customerId": "26.158.183/0004-04",
    "customer": "Perolab",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 92,
    "bank": "Asaas"
  },
  {
    "id": "tx-0056",
    "date": "2025-08-26",
    "description": "Taxa de mensageria",
    "history": "Tarifas de mensageria",
    "customerId": "26.158.183/0004-04",
    "customer": "Perolab",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 81,
    "bank": "Asaas"
  },
  {
    "id": "tx-0057",
    "date": "2025-08-26",
    "description": "Transação via Pix",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "JULIO CESAR RODRIGUES PIRES",
    "typeId": 2,
    "type": "Debito",
    "amount": 2299.0,
    "accountId": 104,
    "bank": "Asaas"
  },
  {
    "id": "tx-0058",
    "date": "2025-09-15",
    "description": "Cobrança recebida",
    "history": "Mensalidade",
    "customerId": "54.687.930/0001-94",
    "customer": "FarmaFormula",
    "typeId": 1,
    "type": "Credito",
    "amount": 2000.0,
    "accountId": 3,
    "bank": "Asaas"
  },
  {
    "id": "tx-0059",
    "date": "2025-09-15",
    "description": "Taxa de boleto",
    "history": "Tarifas de boletos",
    "customerId": "54.687.930/0001-94",
    "customer": "FarmaFormula",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 92,
    "bank": "Asaas"
  },
  {
    "id": "tx-0060",
    "date": "2025-09-15",
    "description": "Taxa de mensageria",
    "history": "Tarifas de mensageria",
    "customerId": "54.687.930/0001-94",
    "customer": "FarmaFormula",
    "typeId": 2,
    "type": "Debito",
    "amount": 0.99,
    "accountId": 81,
    "bank": "Asaas"
  },
  {
    "id": "tx-0061",
    "date": "2025-09-17",
    "description": "Transação via Pix",
    "history": "Transferencia entre contas",
    "customerId": "41.655.312/0001-10",
    "customer": "JULIO CESAR RODRIGUES PIRES M",
    "typeId": 2,
    "type": "Debito",
    "amount": 1998.12,
    "accountId": 104,
    "bank": "Asaas"
  },
  {
    "id": "tx-0062",
    "date": "2025-09-10",
    "description": "PIX RECEBIDO",
    "history": "Transferencia entre contas",
    "customerId": "41655312000110.0",
    "customer": "41.655.312 JULIO CESAR RODRIGUES PIRES",
    "typeId": 1,
    "type": "Credito",
    "amount": 30.0,
    "accountId": 106,
    "bank": "Santander"
  },
  {
    "id": "tx-0063",
    "date": "2025-09-10",
    "description": "PIX RECEBIDO",
    "history": "Transferencia entre contas",
    "customerId": "41655312000110.0",
    "customer": "41.655.312 JULIO CESAR RODRIGUES PIRES",
    "typeId": 1,
    "type": "Credito",
    "amount": 30.0,
    "accountId": 106,
    "bank": "Santander"
  },
  {
    "id": "tx-0064",
    "date": "2025-09-10",
    "description": "PIX RECEBIDO",
    "history": "Transferencia entre contas",
    "customerId": "41655312000110.0",
    "customer": "41.655.312 JULIO CESAR RODRIGUES PIRES",
    "typeId": 1,
    "type": "Credito",
    "amount": 30.0,
    "accountId": 106,
    "bank": "Santander"
  },
  {
    "id": "tx-0065",
    "date": "2025-09-11",
    "description": "COMPRA CARTAO DEB MC 11/09",
    "history": "Combustivel",
    "customerId": "nan",
    "customer": "POSTO CATATAU VIII",
    "typeId": 2,
    "type": "Debito",
    "amount": 100.0,
    "accountId": 33,
    "bank": "Santander"
  },
  {
    "id": "tx-0066",
    "date": "2025-09-11",
    "description": "PIX RECEBIDO",
    "history": "Transferencia entre contas",
    "customerId": "41655312000110.0",
    "customer": "41.655.312 JULIO CESAR RODRIGUES PIRES",
    "typeId": 1,
    "type": "Credito",
    "amount": 7129.65,
    "accountId": 106,
    "bank": "Santander"
  },
  {
    "id": "tx-0067",
    "date": "2025-09-12",
    "description": "COMPRA CARTAO DEB MC 12/09",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "MEGA BOLO",
    "typeId": 2,
    "type": "Debito",
    "amount": 5.0,
    "accountId": 65,
    "bank": "Santander"
  },
  {
    "id": "tx-0068",
    "date": "2025-09-15",
    "description": "COMPRA CARTAO DEB MC 15/09",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "FRANCISCO JOSE DE S",
    "typeId": 2,
    "type": "Debito",
    "amount": 6.5,
    "accountId": 65,
    "bank": "Santander"
  },
  {
    "id": "tx-0069",
    "date": "2025-09-15",
    "description": "PIX ENVIADO",
    "history": "Pilhas",
    "customerId": "nan",
    "customer": "AMAZON COM BR",
    "typeId": 2,
    "type": "Debito",
    "amount": 46.94,
    "accountId": 44,
    "bank": "Santander"
  },
  {
    "id": "tx-0070",
    "date": "2025-09-15",
    "description": "COMPRA CARTAO DEB MC 15/09",
    "history": "Combustivel",
    "customerId": "nan",
    "customer": "POSTO CATATAU",
    "typeId": 2,
    "type": "Debito",
    "amount": 150.0,
    "accountId": 33,
    "bank": "Santander"
  },
  {
    "id": "tx-0071",
    "date": "2025-09-15",
    "description": "PIX RECEBIDO 06780700320",
    "history": "Esporadico",
    "customerId": "nan",
    "customer": "JOSE INACIO SOUSA ALBUQUERQUE",
    "typeId": 1,
    "type": "Credito",
    "amount": 650.0,
    "accountId": 2,
    "bank": "Santander"
  },
  {
    "id": "tx-0072",
    "date": "2025-09-17",
    "description": "COMPRA CARTAO DEB MC 17/09",
    "history": "Copos descartaveis",
    "customerId": "nan",
    "customer": "MP .TEIXEIRASACOL",
    "typeId": 2,
    "type": "Debito",
    "amount": 5.2,
    "accountId": 102,
    "bank": "Santander"
  },
  {
    "id": "tx-0073",
    "date": "2025-09-17",
    "description": "COMPRA CARTAO DEB MC 17/09",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "LIPI SUPERMERCADO",
    "typeId": 2,
    "type": "Debito",
    "amount": 4.39,
    "accountId": 65,
    "bank": "Santander"
  },
  {
    "id": "tx-0074",
    "date": "2025-09-17",
    "description": "PIX RECEBIDO 41655312000110",
    "history": "Transferencia entre contas",
    "customerId": "41655312000110.0",
    "customer": "41.655.312 JULIO CESAR RODRIGUES PIRES",
    "typeId": 1,
    "type": "Credito",
    "amount": 1998.12,
    "accountId": 106,
    "bank": "Santander"
  },
  {
    "id": "tx-0075",
    "date": "2025-09-18",
    "description": "COMPRA CARTAO DEB MC 18/09",
    "history": "Lanches para colaboradores",
    "customerId": "nan",
    "customer": "R G MOREIRA SOUZA C",
    "typeId": 2,
    "type": "Debito",
    "amount": 7.49,
    "accountId": 65,
    "bank": "Santander"
  },
  {
    "id": "tx-0076",
    "date": "2025-09-19",
    "description": "PIX RECEBIDO",
    "history": "Esporadico",
    "customerId": "99256177587.0",
    "customer": "DANILA C M CERQUEIRA",
    "typeId": 1,
    "type": "Credito",
    "amount": 1000.0,
    "accountId": 2,
    "bank": "Santander"
  }
];

export const mockMonthly: { 
  month: MockMonthlyType[],
  averageOrderValueFixed: number,
  averageOrderValueEvent: number 
} = createMockMonthly(mockTransactions);

export const chartAccounts: ChartAccountsType[] = [
  { id: 1, type: "Receitas", subcategories: [
    { accountId: 2, categories: "Projetos Avulsos", subordinate: "Receitas Variáveis" },
    { accountId: 3, categories: "Contratos Mensais", subordinate: "Receita Fixo" },
    { accountId: 4, categories: "Resgate de Aplicação", subordinate: "Retorno de Capital" },
    { accountId: 5, categories: "Juros e Multas", subordinate: "Outras Receitas" },
    { accountId: 106, categories: "Transferências", subordinate: "" }
  ] },
  { id: 2, type: "Despesas", subcategories: [
    { accountId: 1, categories: "Adiantamento de Salário", subordinate:	"Despesas Com Colaboradores" },
    { accountId: 6, categories:	"Agua", subordinate: "Despesas Administrativas" },
    { accountId: 7, categories: "Alugueis", subordinate: "Despesas Administrativas" },
    { accountId: 8,	categories: "Aplicações", subordinate: "Investimentos" },
    { accountId: 9, categories:	"Ativo Imobilizado", subordinate: "" },
    { accountId: 10, categories: "Beneficios Não Obrigatorios", subordinate: "Despesas Com Colaboradores" },
    { accountId: 12, categories: "Bonus por Metas", subordinate: "Despesas Com Colaboradores" },
    { accountId: 13, categories: "Brindes", subordinate: "Eventos e Confraternizações" },
    { accountId: 14, categories: "Comissão dos Colaboradores", subordinate: "Despesas Com Colaboradores" },
    { accountId: 17, categories: "Bolsa Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 19, categories: "Folha de Pagamento", subordinate: "Despesas Com Colaboradores" },
    { accountId: 20, categories: "Compras", subordinate: "" },
    { accountId: 21, categories: "Compras Esporádicas", subordinate: "Despesas Administrativas" },
    { accountId: 22, categories: "Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 23, categories: "Construções/Reformas", subordinate: "Despesas Administrativas" },
    { accountId: 24, categories: "Consultorias", subordinate: "Despesas Administrativas" },
    { accountId: 27, categories: "DAS Simples Nacional", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 29, categories: "Decimo Terceiro Salario", subordinate: "Despesas Com Colaboradores" },
    { accountId: 30, categories: "Despesas Administrativas", subordinate: "" },
    { accountId: 31, categories: "Despesas Com Clientes", subordinate: "Despesas Administrativas" },
    { accountId: 32, categories: "Despesas Com Colaboradores", subordinate: "" },
    { accountId: 33, categories: "Despesas Com Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 34, categories: "Despesas Com Viagens e Hospedagens", subordinate: "Despesas Administrativas" },
    { accountId: 35, categories: "Despesas de Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 36, categories: "Despesas Eventuais", subordinate: "" },
    { accountId: 37, categories: "Despesas Operacionais", subordinate: "" },
    { accountId: 38, categories: "Devoluções", subordinate: "Outras Despesas" },
    { accountId: 39, categories: "Emprestimos", subordinate: "Emprestimos e Financiamentos" },
    { accountId: 40, categories: "Emprestimos e Financiamentos", subordinate: "" },
    { accountId: 41, categories: "Emprestimos Internos", subordinate: "Outras Despesas" },
    { accountId: 42, categories: "Encargos Bancários", subordinate: "" },
    { accountId: 43, categories: "Energia", subordinate: "Despesas Administrativas" },
    { accountId: 44, categories: "Equip. Uso e Consumo", subordinate: "Despesas Administrativas" },
    { accountId: 45, categories: "Eventos e Confraternizações", subordinate: "" },
    { accountId: 48, categories: "Férias", subordinate: "Despesas Com Colaboradores" },
    { accountId: 52, categories: "Impostos", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 53, categories: "Impostos Mensais e Trimestrais", subordinate: "" },
    { accountId: 56, categories: "Integralização de Capital", subordinate: "Investimentos" },
    { accountId: 57, categories: "Internet", subordinate: "Despesas Administrativas" },
    { accountId: 58, categories: "Investimentos", subordinate: "" },
    { accountId: 59, categories: "IPTU", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 60, categories: "IPVA", subordinate: "Despesas Administrativas" },
    { accountId: 61, categories: "Jantares/Almoços Em Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 62, categories: "Juros de Emprestimos", subordinate: "Emprestimos e Financiamentos" },
    { accountId: 63, categories: "Juros e Multas", subordinate: "Despesas Administrativas" },
    { accountId: 64, categories: "Juros Utiliz Ch Especial", subordinate: "Encargos Bancários" },
    { accountId: 65, categories: "Lanches e Refeições", subordinate: "Despesas Com Colaboradores" },
    { accountId: 66, categories: "Lembranças e Troféus", subordinate: "Eventos e Confraternizações" },
    { accountId: 67, categories: "Manutençao da Conta", subordinate: "Encargos Bancários" },
    { accountId: 68, categories: "Manutenção de Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 69, categories: "Manutenção de Informatica", subordinate: "Despesas Administrativas" },
    { accountId: 70, categories: "Manutenção de Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 71, categories: "Manutenção Interna (máquinas, Luzes...)", subordinate: "Despesas Administrativas" },
    { accountId: 72, categories: "Manutenção Predial", subordinate: "Despesas Administrativas" },
    { accountId: 73, categories: "Maquinas e Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 74, categories: "Materiais de Higiene e Limpeza", subordinate: "Despesas Administrativas" },
    { accountId: 75, categories: "Material de Escritório", subordinate: "Despesas Administrativas" },
    { accountId: 76, categories: "Material Gráfico", subordinate: "Despesas Administrativas" },
    { accountId: 77, categories: "Moveis e Utensilios", subordinate: "Despesas Administrativas" },
    { accountId: 79, categories: "Outras Despesas", subordinate: "" },
    { accountId: 80, categories: "Outras Despesas", subordinate: "Despesas Eventuais" },
    { accountId: 81, categories: "Outras Tarifas", subordinate: "Encargos Bancários" },
    { accountId: 84, categories: "Rescisões", subordinate: "Despesas Com Colaboradores" },
    { accountId: 86, categories: "Seguros", subordinate: "Despesas Administrativas" },
    { accountId: 87, categories: "Serviços Extraordinários", subordinate: "Eventos e Confraternizações" },
    { accountId: 88, categories: "Serviços Terceirizados", subordinate: "Despesas Administrativas" },
    { accountId: 89, categories: "Simples Nacional", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 90, categories: "Sistemas Contratados", subordinate: "Despesas Administrativas" },
    { accountId: 91, categories: "Tarifas Bancárias", subordinate: "Encargos Bancários" },
    { accountId: 92, categories: "Tarifas de Boletos", subordinate: "Encargos Bancários" },
    { accountId: 93, categories: "Tarifas Pix", subordinate: "Encargos Bancários" },
    { accountId: 94, categories: "Tarifas Utiliz. Ch. Esp", subordinate: "Encargos Bancários" },
    { accountId: 95, categories: "Telefonia e Planos", subordinate: "Despesas Administrativas" },
    { accountId: 96, categories: "Terrenos e Imoveis", subordinate: "Despesas Administrativas" },
    { accountId: 97, categories: "Transferencias", subordinate: "" },
    { accountId: 98, categories: "Treinamentos e Cursos", subordinate: "Despesas Administrativas" },
    { accountId: 99, categories: "Uniformes e Crachás", subordinate: "Despesas Com Colaboradores" },
    { accountId: 100, categories: "Vale Transportes", subordinate: "Despesas Com Colaboradores" },
    { accountId: 102, categories: "Copa e Cozinha", subordinate: "Despesas com Colaboradores" },
    { accountId: 104, categories: "Transferências", subordinate: "" }
  ] },
  { id: 3, type: "Custos", subcategories: [
    { accountId: 11, categories: "Benefícios", subordinate: "Custo" },
    { accountId: 15, categories: "Comissões", subordinate: "Custo" },
    { accountId: 16, categories: "Bolsa Estágio", subordinate: "Custo" },
    { accountId: 18, categories: "Folha de Pagamento", subordinate: "Custo" },
    { accountId: 25, categories: "Custo com Sistemas", subordinate: "Custo" },
    { accountId: 26, categories: "Custos", subordinate: "" },
    { accountId: 28, categories: "Décimo Terceiro", subordinate: "Custo" },
    { accountId: 101, categories: "Entregas ao Cliente", subordinate: "Custo" },
    { accountId: 46, categories: "Exames ASO", subordinate: "Custo" },
    { accountId: 47, categories: "Férias", subordinate: "Custo" },
    { accountId: 49, categories: "FGTS", subordinate: "Custo" },
    { accountId: 50, categories: "FGTS Rescisório", subordinate: "Custo" },
    { accountId: 51, categories: "Horas Extras", subordinate: "Custo" },
    { accountId: 54, categories: "INSS", subordinate: "Custo" },
    { accountId: 55, categories: "INSS/IRRF", subordinate: "Custo" },
    { accountId: 103, categories: "Pró-labore", subordinate: "Custo" },
    { accountId: 85, categories: "Rescisões", subordinate: "Custo" },
  ] },
];
