import { ChartAccounts } from "@/lib/types";

export const MONTH_NAME = ['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'];

export const CHART_ACCOUNT: ChartAccounts[] = [
  { id: 1, type: "Receitas", subcategories: [
    { accountId: 2, categories: "Projetos Avulsos", subordinate: "Receitas Variáveis" },
    { accountId: 3, categories: "Contratos Mensais", subordinate: "Receita Fixo" },
    { accountId: 4, categories: "Resgate de Aplicação", subordinate: "Retorno de Capital" },
    { accountId: 5, categories: "Juros e Multas", subordinate: "Outras Receitas" },
    { accountId: 111, categories: "Estornos", subordinate: "Outras Receitas" },
    { accountId: 106, categories: "Transferências", subordinate: "" }
  ] },
  { id: 2, type: "Despesas", subcategories: [
    { accountId: 30, categories: "Despesas Administrativas", subordinate: "" },
    { accountId: 6, categories:	"Agua", subordinate: "Despesas Administrativas" },
    { accountId: 7, categories: "Alugueis", subordinate: "Despesas Administrativas" },
    { accountId: 21, categories: "Compras Esporádicas", subordinate: "Despesas Administrativas" },
    { accountId: 23, categories: "Construções/Reformas", subordinate: "Despesas Administrativas" },
    { accountId: 24, categories: "Consultorias", subordinate: "Despesas Administrativas" },
    { accountId: 31, categories: "Despesas Com Clientes", subordinate: "Despesas Administrativas" },
    { accountId: 33, categories: "Despesas Com Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 34, categories: "Despesas Com Viagens e Hospedagens", subordinate: "Despesas Administrativas" },
    { accountId: 43, categories: "Energia", subordinate: "Despesas Administrativas" },
    { accountId: 44, categories: "Equip. Uso e Consumo", subordinate: "Despesas Administrativas" },
    { accountId: 57, categories: "Internet", subordinate: "Despesas Administrativas" },
    { accountId: 60, categories: "IPVA", subordinate: "Despesas Administrativas" },
    { accountId: 63, categories: "Juros e Multas", subordinate: "Despesas Administrativas" },
    { accountId: 68, categories: "Manutenção de Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 69, categories: "Manutenção de Informatica", subordinate: "Despesas Administrativas" },
    { accountId: 70, categories: "Manutenção de Veiculos", subordinate: "Despesas Administrativas" },
    { accountId: 71, categories: "Manutenção Interna (máquinas, Luzes...)", subordinate: "Despesas Administrativas" },
    { accountId: 72, categories: "Manutenção Predial", subordinate: "Despesas Administrativas" },
    { accountId: 73, categories: "Maquinas e Equipamentos", subordinate: "Despesas Administrativas" },
    { accountId: 74, categories: "Materiais de Higiene e Limpeza", subordinate: "Despesas Administrativas" },
    { accountId: 75, categories: "Material de Escritório", subordinate: "Despesas Administrativas" },
    { accountId: 76, categories: "Material Gráfico", subordinate: "Despesas Administrativas" },
    { accountId: 77, categories: "Moveis e Utensilios", subordinate: "Despesas Administrativas" },
    { accountId: 86, categories: "Seguros", subordinate: "Despesas Administrativas" },
    { accountId: 88, categories: "Serviços Terceirizados", subordinate: "Despesas Administrativas" },
    { accountId: 90, categories: "Sistemas Contratados", subordinate: "Despesas Administrativas" },
    { accountId: 95, categories: "Telefonia e Planos", subordinate: "Despesas Administrativas" },
    { accountId: 96, categories: "Terrenos e Imoveis", subordinate: "Despesas Administrativas" },
    { accountId: 98, categories: "Treinamentos e Cursos", subordinate: "Despesas Administrativas" },
    { accountId: 112, categories: "Taxas e Contribuições", subordinate: "Despesas Administrativas" },
    { accountId: 8,	categories: "Aplicações", subordinate: "Investimentos" },
    { accountId: 9, categories:	"Ativo Imobilizado", subordinate: "" },
    { accountId: 1, categories: "Adiantamento de Salário", subordinate:	"Despesas Com Colaboradores" },
    { accountId: 10, categories: "Beneficios Não Obrigatorios", subordinate: "Despesas Com Colaboradores" },
    { accountId: 12, categories: "Bonus por Metas", subordinate: "Despesas Com Colaboradores" },
    { accountId: 13, categories: "Brindes", subordinate: "Eventos e Confraternizações" },
    { accountId: 14, categories: "Comissão dos Colaboradores", subordinate: "Despesas Com Colaboradores" },
    { accountId: 17, categories: "Bolsa Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 19, categories: "Folha de Pagamento", subordinate: "Despesas Com Colaboradores" },
    { accountId: 20, categories: "Compras", subordinate: "" },
    { accountId: 22, categories: "Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 29, categories: "Decimo Terceiro Salario", subordinate: "Despesas Com Colaboradores" },
    { accountId: 32, categories: "Despesas Com Colaboradores", subordinate: "" },
    { accountId: 35, categories: "Despesas de Estágio", subordinate: "Despesas Com Colaboradores" },
    { accountId: 36, categories: "Despesas Eventuais", subordinate: "" },
    { accountId: 38, categories: "Devoluções", subordinate: "Outras Despesas" },
    { accountId: 39, categories: "Emprestimos", subordinate: "Emprestimos e Ficiamentos" },
    { accountId: 40, categories: "Emprestimos e Ficiamentos", subordinate: "" },
    { accountId: 41, categories: "Emprestimos Internos", subordinate: "Outras Despesas" },
    { accountId: 42, categories: "Encargos Bancários", subordinate: "" },
    { accountId: 45, categories: "Eventos e Confraternizações", subordinate: "" },
    { accountId: 48, categories: "Férias", subordinate: "Despesas Com Colaboradores" },
    { accountId: 52, categories: "Impostos", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 53, categories: "Impostos Mensais e Trimestrais", subordinate: "" },
    { accountId: 56, categories: "Integralização de Capital", subordinate: "Investimentos" },
    { accountId: 58, categories: "Investimentos", subordinate: "" },
    { accountId: 59, categories: "IPTU", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 61, categories: "Jantares/Almoços Em Confraternizações", subordinate: "Eventos e Confraternizações" },
    { accountId: 62, categories: "Juros de Emprestimos", subordinate: "Emprestimos e Ficiamentos" },
    { accountId: 64, categories: "Juros Utiliz Ch Especial", subordinate: "Encargos Bancários" },
    { accountId: 65, categories: "Lanches e Refeições", subordinate: "Despesas Com Colaboradores" },
    { accountId: 66, categories: "Lembranças e Troféus", subordinate: "Eventos e Confraternizações" },
    { accountId: 67, categories: "Manutençao da Conta", subordinate: "Encargos Bancários" },
    { accountId: 79, categories: "Outras Despesas", subordinate: "" },
    { accountId: 80, categories: "Outras Despesas", subordinate: "Despesas Eventuais" },
    { accountId: 81, categories: "Outras Tarifas", subordinate: "Encargos Bancários" },
    { accountId: 84, categories: "Rescisões", subordinate: "Despesas Com Colaboradores" },
    { accountId: 87, categories: "Serviços Extraordinários", subordinate: "Eventos e Confraternizações" },
    { accountId: 89, categories: "Simples Nacional", subordinate: "Impostos Mensais e Trimestrais" },
    { accountId: 91, categories: "Tarifas Bancárias", subordinate: "Encargos Bancários" },
    { accountId: 92, categories: "Tarifas de Boletos", subordinate: "Encargos Bancários" },
    { accountId: 93, categories: "Tarifas Pix", subordinate: "Encargos Bancários" },
    { accountId: 94, categories: "Tarifas Utiliz. Cartão", subordinate: "Encargos Bancários" },
    { accountId: 97, categories: "Transferencias", subordinate: "" },
    { accountId: 99, categories: "Uniformes e Crachás", subordinate: "Despesas Com Colaboradores" },
    { accountId: 100, categories: "Vale Transportes", subordinate: "Despesas Com Colaboradores" },
    { accountId: 102, categories: "Copa e Cozinha", subordinate: "Despesas com Colaboradores" },
    { accountId: 104, categories: "Transferências", subordinate: "" }
  ] },
  { id: 3, type: "Custos", subcategories: [
    { accountId: 26, categories: "Custos", subordinate: "" },
    { accountId: 11, categories: "Benefícios", subordinate: "Custo" },
    { accountId: 15, categories: "Comissões", subordinate: "Custo" },
    { accountId: 16, categories: "Bolsa Estágio", subordinate: "Custo" },
    { accountId: 18, categories: "Folha de Pagamento", subordinate: "Custo" },
    { accountId: 25, categories: "Custo com Sistemas", subordinate: "Custo" },
    { accountId: 28, categories: "Décimo Terceiro", subordinate: "Custo" },
    { accountId: 101, categories: "Entregas ao Cliente", subordinate: "Custo" },
    { accountId: 46, categories: "Exames ASO", subordinate: "Custo" },
    { accountId: 47, categories: "Férias", subordinate: "Custo" },
    { accountId: 49, categories: "FGTS", subordinate: "Custo" },
    { accountId: 50, categories: "FGTS Rescisório", subordinate: "Custo" },
    { accountId: 51, categories: "Horas Extras", subordinate: "Custo" },
    { accountId: 54, categories: "INSS", subordinate: "Custo" },
    { accountId: 55, categories: "INSS/IRRF", subordinate: "Custo" },
    { accountId: 85, categories: "Rescisões", subordinate: "Custo" },
    { accountId: 103, categories: "Pró-labore", subordinate: "Custo" },
  ] },
];